name: Documentation Update
on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch: # on button click

jobs:

  sync:
    name: Update Documentation and push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Update Docs
        run: npm run docs

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Documentation Auto Updater
          author_email: documentation@auto-updater.com
          message: 'Documentation Update'
          add: 'docs/*'
