name: Release Alpha

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha' # Push events to matching v*-alpha, i.e. v1.0.0-alpha
      - '!*-no-ci'
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.CONSECUTIVE_ACTION_TRIGGER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Get the version
        id: get_version
        run: echo "::set-output name=VERSION::${GITHUB_REF}"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.get_version.outputs.VERSION }}
          prerelease: true
          files: |
            Release.txt
            README.md
            LICENSE.md
#
